version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    ignore:
      # Ignore patch updates for non-security dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "mypy"
          - "ruff"
          - "flake8*"
        exclude-patterns:
          - "pytest-cov"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
