version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore patch updates for non-security dependencies
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "black"
          - "mypy"
          - "ruff"
          - "flake8*"
        exclude-patterns:
          - "pytest-cov"
      security-dependencies:
        patterns:
          - "cryptography"
          - "pyjwt"
          - "requests"
          - "urllib3"
          - "pydantic"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
