name: Advanced Linting

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/advanced-lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/advanced-lint.yml'
  workflow_dispatch:

jobs:
  lint:
    name: Comprehensive Code Quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      
      - name: Ruff Linting
        uses: charliermarsh/ruff-action@v2
        with:
          args: --select=E,F,W,I,N,B,RUF,PL,UP,S,BLE,A,C4,T20,PT,RET,SIM,ERA,ICN
      
      - name: Black code formatting check
        run: |
          poetry run black --check --verbose .
      
      - name: Check import order with isort
        run: |
          poetry run isort --check-only --profile black --verbose .
      
      - name: Type check with mypy
        run: |
          poetry run mypy src tests
      
      - name: Security scan with bandit
        run: |
          poetry run bandit -r src -c pyproject.toml

      - name: Complexity analysis with radon
        run: |
          poetry run pip install radon
          poetry run radon cc src -a -nc

      - name: Documentation check with pydocstyle
        run: |
          poetry run pip install pydocstyle
          poetry run pydocstyle src

      - name: Check for fixme/todo markers
        run: |
          poetry run ruff check . --select=F841,F842,F401,F405,F403,F821 --statistics 
