name: Code Quality Coverage

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/code-coverage.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/code-coverage.yml'
  workflow_dispatch:

jobs:
  coverage:
    name: Code Quality Coverage Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      
      - name: Run tests with coverage
        run: |
          poetry run pytest --cov=src --cov-report=xml --cov-report=term
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
      
      - name: Generate HTML coverage report
        run: |
          poetry run pytest --cov=src --cov-report=html
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: htmlcov/
      
      - name: Check coverage thresholds by module
        run: |
          echo "Checking API coverage"
          poetry run coverage report --include="src/**/api/*.py" --fail-under=75
          echo "Checking core functionality coverage"
          poetry run coverage report --include="src/**/core/*.py" --fail-under=80
          echo "Checking utilities coverage"
          poetry run coverage report --include="src/**/utils/*.py" --fail-under=85
          echo "Checking overall coverage"
          poetry run coverage report --fail-under=80 
