name: Welcome First-time Contributors

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for filing your first issue in the DC API-X project! 🎉

            Our team will review your issue as soon as possible. In the meantime:

            - Please make sure you've followed our issue template
            - Check if there are any existing issues that might be related
            - Join our community discussions if you'd like to get involved

            We appreciate your contribution and look forward to working with you!
          pr-message: |
            Hello! Thank you for submitting your first pull request to the DC API-X project! 🚀

            Here's what happens next:

            1. Our automated tests will run to verify your changes
            2. A maintainer will review your code
            3. You may be asked to make some adjustments
            4. Once approved, your PR will be merged

            If you have any questions during this process, feel free to ask in the PR comments.

            Thanks for contributing to make our project better!
