name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with dev
          # Ensure wemake-python-styleguide is installed
          pip install flake8 wemake-python-styleguide

      - name: Format check with black
        run: black --check src/ tests/

      - name: Import order check with isort
        run: isort --check src/ tests/

      # Temporarily disabled until all issues are fixed
      # - name: Lint with ruff
      #   run: ruff check src/ tests/

      - name: Lint with wemake-python-styleguide
        run: flake8 src/ tests/ --select=WPS

      - name: Type check with mypy
        run: mypy src/

      - name: Security check with bandit
        run: bandit -r src/
