# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark and Close Stale Issues and PRs

on:
  schedule:
    - cron: "30 1 * * *" # Run at 1:30 AM UTC daily

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Issue config
          stale-issue-message: >
            This issue has been automatically marked as stale because it has had
            no activity for the last 30 days. It will be closed in 14 days if no
            further activity occurs. Thank you for your contributions.

            If you believe this issue is still relevant and should remain open, 
            please comment or remove the stale label.
          close-issue-message: >
            This issue has been automatically closed because it has had no activity
            for the last 44 days (30 days to mark stale + 14 days waiting period).

            If you believe this issue should be reopened, please create a new issue
            with a link to this one.
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          exempt-issue-labels: "bug,enhancement,documentation,security,dependencies"

          # PR config
          stale-pr-message: >
            This pull request has been automatically marked as stale because it has had
            no activity for the last 30 days. It will be closed in 14 days if no
            further activity occurs. Thank you for your contributions.

            If you believe this PR is still relevant and should remain open, 
            please comment or remove the stale label.
          close-pr-message: >
            This pull request has been automatically closed because it has had no activity
            for the last 44 days (30 days to mark stale + 14 days waiting period).

            If you believe this PR should be reopened, please contact a maintainer.
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-pr-label: "stale"
          exempt-pr-labels: "dependencies,wip,work-in-progress,security"

          # General config
          exempt-all-milestones: true
          exempt-all-assignees: false
          operations-per-run: 100
